In [ ]:
import torch
torch.__version__

#Introduction to *tensor*

##creating tensor

1.**scalar**

In [ ]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

2.**vector**

In [ ]:
vector = torch.tensor([1,2]) #no of opening sq bracket is equal to ndim
vector

tensor([1, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape #no of element in tensors

torch.Size([2])

3.**Matrix**

In [ ]:
matrix=torch.tensor([[1,2,3,4],[4,5,6,6],[7,8,9,1]])
matrix

tensor([[1, 2, 3, 4],
        [4, 5, 6, 6],
        [7, 8, 9, 1]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape  # rows and columns multiply them to get total no of elements

torch.Size([3, 4])

4.**Tensor**

In [ ]:
tensor = torch.tensor([[[1,2,3,4],
                        [4,5,6,7],
                         [7,8,9,10]]])
tensor

tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  7],
         [ 7,  8,  9, 10]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 4])

## Random Tensor

In [ ]:
random=torch.rand(size=(10,5))

In [ ]:
random

tensor([[0.4985, 0.9987, 0.6049, 0.5229, 0.6974],
        [0.2505, 0.3624, 0.4621, 0.7145, 0.5058],
        [0.0518, 0.2492, 0.2395, 0.4233, 0.0022],
        [0.6848, 0.7497, 0.2489, 0.3490, 0.1953],
        [0.2792, 0.2526, 0.3792, 0.7686, 0.6907],
        [0.7526, 0.1184, 0.8699, 0.8391, 0.0532],
        [0.1705, 0.2914, 0.5682, 0.0380, 0.2715],
        [0.6987, 0.0944, 0.6719, 0.3782, 0.8738],
        [0.7267, 0.9486, 0.4388, 0.4589, 0.0359],
        [0.3525, 0.0389, 0.3880, 0.1319, 0.5018]])

In [ ]:
bigger_tensor=torch.rand(5,3,4)
bigger_tensor

tensor([[[0.8077, 0.9322, 0.5680, 0.5034],
         [0.2074, 0.4779, 0.4203, 0.4014],
         [0.0436, 0.6490, 0.9007, 0.8274]],

        [[0.3785, 0.7518, 0.2839, 0.7220],
         [0.8421, 0.2474, 0.6834, 0.0551],
         [0.7824, 0.7901, 0.9596, 0.6065]],

        [[0.5926, 0.7300, 0.9768, 0.9680],
         [0.1494, 0.9826, 0.7921, 0.5842],
         [0.9628, 0.3192, 0.5750, 0.1538]],

        [[0.2540, 0.9703, 0.5020, 0.3018],
         [0.8832, 0.1921, 0.7686, 0.2524],
         [0.3668, 0.0484, 0.7829, 0.7032]],

        [[0.7265, 0.5794, 0.1412, 0.8105],
         [0.9284, 0.9444, 0.6538, 0.5344],
         [0.8025, 0.5484, 0.5738, 0.4225]]])

**zeros and ones**

In [ ]:
zeros = torch.zeros(5,3,4)

In [ ]:
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(4,3,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

**Creating arange and tensors_like**

In [ ]:
x = torch.arange(1,10) # start and end params
x # always print from start to end-1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = torch.arange(1,10,2) # start , end , stepsize

In [ ]:
x

tensor([1, 3, 5, 7, 9])

In [ ]:
x = torch.arange(0,50,2) # start and end params
x # always print from start to end-1

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48])

**tensors_like**

In [ ]:
sample = torch.rand(3,4)
sample

tensor([[0.7506, 0.6641, 0.3130, 0.9395],
        [0.3158, 0.9486, 0.2662, 0.1538],
        [0.4508, 0.7602, 0.8260, 0.4980]])

In [ ]:
zeros = torch.zeros_like(sample)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones_like(sample)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**torch.eye**

In [ ]:
eye = torch.eye(10) # Identity matrix with only elements in diagonal with n * n matrix
eye

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**torch.full**

In [ ]:
full = torch.full((2,5),10)
full

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

**torch.linespace**

In [ ]:
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [ ]:
linear_tensor = torch.linspace(1,10,50) # stops at en not line arange and it create n steps between them only
linear_tensor

tensor([ 1.0000,  1.1837,  1.3673,  1.5510,  1.7347,  1.9184,  2.1020,  2.2857,
         2.4694,  2.6531,  2.8367,  3.0204,  3.2041,  3.3878,  3.5714,  3.7551,
         3.9388,  4.1224,  4.3061,  4.4898,  4.6735,  4.8571,  5.0408,  5.2245,
         5.4082,  5.5918,  5.7755,  5.9592,  6.1429,  6.3265,  6.5102,  6.6939,
         6.8776,  7.0612,  7.2449,  7.4286,  7.6122,  7.7959,  7.9796,  8.1633,
         8.3469,  8.5306,  8.7143,  8.8980,  9.0816,  9.2653,  9.4490,  9.6327,
         9.8163, 10.0000])

**Tensor Datatypes**

In [ ]:
sample = torch.rand(3,4)  #default float 32 for backward propogration it is useful
sample

tensor([[0.0992, 0.2705, 0.3298, 0.0929],
        [0.5143, 0.5082, 0.7539, 0.6718],
        [0.8547, 0.6662, 0.1022, 0.3406]])

In [ ]:
sample.dtype

torch.float32

In [ ]:
sample = torch.arange(3.,4.,dtype=int)
sample

tensor([3])

In [ ]:
sample.dtype

torch.int64

**Change tensor datatype**

In [ ]:
tensor = torch.arange(1.,10.)
tensor,tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [ ]:
tensor_float16 = tensor.type(torch.float16)  # quality down
tensor_float16,tensor_float16.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16),
 torch.float16)

In [ ]:
tensor_float16 = tensor.type(torch.int8)  # quality down
tensor_float16,tensor_float16.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8), torch.int8)

##Getting Information from tensor

shape:
dtype:
device:

In [ ]:
x = torch.rand(3,4)
x

tensor([[0.3004, 0.6601, 0.2266, 0.8444],
        [0.8083, 0.8055, 0.5530, 0.0628],
        [0.9157, 0.4161, 0.3926, 0.8140]])

In [ ]:
x.shape

torch.Size([3, 4])

In [ ]:
x.dtype

torch.float32

In [ ]:
x.device

device(type='cpu')

## Manipulating tensor
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

1. Addition

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
dd = tensor + 10

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
dd

tensor([11, 12, 13])

In [ ]:
tensor1 = tensor + dd
tensor1

tensor([12, 14, 16])

In [ ]:
tensor2=torch.add(tensor,dd)
tensor2

tensor([12, 14, 16])

2.Subtraction

In [ ]:
tensor1 = tensor - dd
tensor1

tensor([-10, -10, -10])

In [ ]:
dd = tensor - 10
dd

tensor([-9, -8, -7])

In [ ]:
tensor2=torch.sub(tensor1,dd)
tensor2

tensor([-1, -2, -3])

3. Multiplication(Element wise)

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

4.Division


In [ ]:
tensor = torch.tensor([2,4,6,8])
tensor

tensor([2, 4, 6, 8])

In [ ]:
tensor/2

tensor([1., 2., 3., 4.])

In [ ]:
tensor/tensor

tensor([1., 1., 1., 1.])

In [ ]:
torch.div(tensor,2)

tensor([1., 2., 3., 4.])

5. Matrix Multiplication

In [ ]:
matrix1=torch.tensor([[1,2],
                      [3,4]])
matrix2=torch.tensor([[5,6],
                      [7,8]])
matrix1,matrix2

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [ ]:
matrix1.shape,matrix2.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [ ]:
matrix1*matrix2 # element wise multiplication using *

tensor([[ 5, 12],
        [21, 32]])

In [ ]:
matrix1@matrix2 # matrix multiplication using @

tensor([[19, 22],
        [43, 50]])

In [ ]:
torch.mm(matrix1,matrix2) # matrix multiplication using torch.mm

tensor([[19, 22],
        [43, 50]])

In [ ]:
torch.matmul(matrix1,matrix2) # matrix multiplication using torch.matmul

tensor([[19, 22],
        [43, 50]])

## One of the most common error in deep learning (Shape error)

In [ ]:
tensor_a = torch.tensor([[1,2],
                      [3,4],
                      [5,6]],dtype=torch.float32)
tensor_b = torch.tensor([[7,10],
                      [8,11],
                      [9,12]],dtype=torch.float32)
tensor_a,tensor_b

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]))

In [ ]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_a@tensor_b # due to shape error to resolve this we have to make the transpose

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a,tensor_a.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 torch.Size([3, 2]))

In [ ]:
tensor_b,tensor_b.shape

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [ ]:
tensor_b

tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])

In [ ]:
tensor=tensor_b.T
tensor,tensor.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [ ]:
tensor_a@tensor # due to shape error to resolve this we have to make the transpose

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## finding the mean , min , max,sum

In [ ]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.min()

tensor(1)

In [ ]:
x.max()

tensor(9)

In [ ]:
x.sum()

tensor(45)

In [ ]:
x.mean() # here we require floating point

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
y = x.type(torch.float32)
y

In [ ]:
y.mean()

In [ ]:
torch.min(y),torch.max(y),torch.mean(y),torch.sum(y)

**positional max and min**

In [ ]:
sample = torch.arange(1,5)
sample

In [ ]:
sample.min()

In [ ]:
sample.argmin() # index of min value

In [ ]:
sample.argmax() # index of max value

## reshaping,stacking,squeezing,unsqueez,permute

**reshape**

In [ ]:
x = torch.arange(1.,9.)
x,x.shape

In [ ]:
x.reshape(4,2),x.reshape(2,4)

In [ ]:
x.reshape(8,1),x.reshape(1,8),x.reshape(2,2,2)

**view()**

In [ ]:
y = torch.arange(1.,9.)

In [ ]:
y

In [ ]:
y_view = y.view(8,1)
y_view

In [ ]:
y_view = y.view(2,4)
y_view

In [ ]:
y_view[0,0] = 5 # with help of indexing we used this
y_view

In [ ]:
y # changed the value in original tensor

NameError: name 'y' is not defined

torch.stack()

In [ ]:
tensor =  torch.arange(1.,8.)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensor_stacked = torch.stack([tensor,tensor,tensor,tensor],dim=0) # concatenate two tensor of same size 0 for row wise  1 for column wise
tensor_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [ ]:
tensor_stacked1 = torch.stack([tensor,tensor,tensor,tensor],dim=1) # concatenate two tensor of same size 0 for row wise  1 for column wise
tensor_stacked1

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

**torch.unsqueez()**

In [ ]:
x = torch.arange(1,10)
x,x.shape,x.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), 1)

In [ ]:
x_unsqueezed = x.unsqueeze(dim=0) # add single dimension in 0 index
x_unsqueezed,x_unsqueezed.shape,x_unsqueezed.ndim

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]), 2)

In [ ]:
x_unsqueezed1 = x.unsqueeze(dim=1) # add single dimension in 1 index
x_unsqueezed1,x_unsqueezed1.shape,x_unsqueezed1.ndim

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]),
 2)

torch.squeez()

In [ ]:
x_unsqueezed.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x_unsqueezed.squeeze()
x_squeezed,x_squeezed.shape,x_squeezed.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), 1)

**permute**

In [ ]:
x = torch.rand(2,3,5)
x

tensor([[[0.9255, 0.0434, 0.5598, 0.7861, 0.7609],
         [0.0068, 0.0462, 0.7082, 0.3937, 0.2298],
         [0.3002, 0.5626, 0.3442, 0.6935, 0.7979]],

        [[0.0215, 0.1281, 0.2894, 0.7914, 0.2858],
         [0.6467, 0.8352, 0.2651, 0.4249, 0.9888],
         [0.0682, 0.3140, 0.0156, 0.2091, 0.2706]]])

In [ ]:
x.shape

torch.Size([2, 3, 5])

In [ ]:
x_permuted = x.permute(2,1,0) # rearange the dimensions we can use permute for changing the dimension using their index
x_permuted.shape

torch.Size([5, 3, 2])

## Indexing(Selecting data from tensors)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[0,1,1]

tensor(5)

##Pytorch tensor and Numpy

In [ ]:
import numpy as np


In [ ]:
array = np.arange(1.,8.)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
numpy_array = tensor.numpy()
numpy_array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
array,tensor,numpy_array

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

## Reproducibility

In [ ]:
random_a = torch.rand(3,4)
random_a

tensor([[0.9733, 0.3063, 0.8674, 0.4838],
        [0.6028, 0.5981, 0.9723, 0.9481],
        [0.8696, 0.8309, 0.2965, 0.6900]])

In [ ]:
random_b = torch.rand(3,4)
random_b

tensor([[0.7226, 0.7527, 0.4492, 0.2886],
        [0.5041, 0.9606, 0.6831, 0.5812],
        [0.0520, 0.7810, 0.0198, 0.4093]])

In [ ]:
random_seed = 42  #same result is reproduced using this
torch.manual_seed(random_seed)
random_c = torch.rand(3,4)
random_c

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
random_seed = 42
torch.manual_seed(random_seed)
random_d = torch.rand(3,4)
random_d

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [ ]:
random_seed = 50
torch.manual_seed(random_seed)
random_e = torch.rand(3,4)
random_e

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])

## Running Tensors on GPU's

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [ ]:
tensor_back_to_cpu = tensor_on_gpu.cpu()
tensor_back_to_cpu

tensor([1, 2, 3])

In [ ]:
tensor_back_to_cpu.device

device(type='cpu')